apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pusehe0dm-nodejs
  janus-idp.io/tekton: pusehe0dm-nodejs
  backstage.io/kubernetes-id: pusehe0dm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pusehe0dm-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
